/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Setup */
        post: operations["setup_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/caps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Caps */
        put: operations["update_caps_budget_caps_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_budget_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Path */
        get: operations["get_path_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{module_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Module */
        get: operations["get_module_modules__module_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{module_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Check */
        post: operations["start_check_modules__module_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checks/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Check */
        post: operations["submit_check_checks__run_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesson */
        get: operations["get_lesson_lessons__lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lesson_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Exercise */
        post: operations["check_exercise_lessons__lesson_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lesson_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Lesson */
        post: operations["complete_lesson_lessons__lesson_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Due Reviews */
        get: operations["due_reviews_reviews_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate Card */
        post: operations["rate_card_reviews__card_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Learned Words */
        get: operations["learned_words_library_words_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/sentences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Learned Sentences */
        get: operations["learned_sentences_library_sentences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/concepts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Learned Concepts */
        get: operations["learned_concepts_library_concepts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skills */
        get: operations["get_skills_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Drill */
        post: operations["start_drill_drills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drills/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Drill */
        post: operations["submit_drill_drills__run_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/placement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Placement */
        post: operations["start_placement_placement_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/placement/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Placement */
        post: operations["submit_placement_placement__run_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        /** Update Settings */
        put: operations["update_settings_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lesson_id}/writing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Lesson Writing */
        post: operations["submit_lesson_writing_lessons__lesson_id__writing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/writing/drills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Writing Drill */
        post: operations["start_writing_drill_writing_drills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/writing/drills/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Writing Drill */
        post: operations["submit_writing_drill_writing_drills__run_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Error Fingerprint */
        get: operations["error_fingerprint_errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthStatus */
        AuthStatus: {
            /** Configured */
            configured: boolean;
            /** Authenticated */
            authenticated: boolean;
        };
        /** BudgetSummary */
        BudgetSummary: {
            /** Month */
            month: string;
            /** Price Version */
            price_version: string;
            /** Services */
            services: {
                [key: string]: components["schemas"]["ServiceSpend"];
            };
            /** By Feature */
            by_feature: components["schemas"]["FeatureSpend"][];
            /** Free Allowances */
            free_allowances: components["schemas"]["FreeAllowance"][];
        };
        /** CapsUpdate */
        CapsUpdate: {
            /** Openai */
            openai: number | string;
            /** Speech */
            speech: number | string;
            /** Total */
            total: number | string;
        };
        /** CheckItemOut */
        CheckItemOut: {
            /** Id */
            id: string;
            /** Skill */
            skill: string;
            exercise: components["schemas"]["ExerciseOut"];
        };
        /** CheckOutcome */
        CheckOutcome: {
            /** Score */
            score: number;
            /** Passed */
            passed: boolean;
            /** Results */
            results: components["schemas"]["ItemResult"][];
            module: components["schemas"]["ModuleSummary"];
        };
        /** CheckResultOut */
        CheckResultOut: {
            /** Correct */
            correct: boolean;
            /** Expected */
            expected: string;
            /** Explanation */
            explanation: string | null;
        };
        /** CheckSubmission */
        CheckSubmission: {
            /** Answers */
            answers: components["schemas"]["ItemAnswer"][];
        };
        /** ConceptOut */
        ConceptOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Body Md */
            body_md: string;
        };
        /** CoverageOut */
        CoverageOut: {
            /** Covered */
            covered: number;
            /** Total */
            total: number;
            /** Percent */
            percent: number;
        };
        /** DrillOut */
        DrillOut: {
            /** Run Id */
            run_id: number;
            /** Skill */
            skill: string;
            /**
             * Deadline
             * Format: date-time
             */
            deadline: string;
            /** Items */
            items: components["schemas"]["CheckItemOut"][];
        };
        /** DrillOutcome */
        DrillOutcome: {
            /** Score */
            score: number;
            /** Results */
            results: components["schemas"]["ItemResult"][];
            level: components["schemas"]["SkillLevelOut"] | null;
        };
        /** DrillStart */
        DrillStart: {
            /**
             * Skill
             * @enum {string}
             */
            skill: "CO" | "CE";
            /**
             * Count
             * @default 10
             */
            count: number;
        };
        /** ErrorFingerprintOut */
        ErrorFingerprintOut: {
            /** Tag */
            tag: string;
            /** Count */
            count: number;
            /** Example */
            example: string;
            /** Correction */
            correction: string;
        };
        /** ExamPlanOut */
        ExamPlanOut: {
            /**
             * Exam Date
             * Format: date
             */
            exam_date: string;
            /** Days Left */
            days_left: number;
            /**
             * Book By
             * Format: date
             */
            book_by: string;
            /**
             * Earliest Retake
             * Format: date
             */
            earliest_retake: string;
            /** Final Phase */
            final_phase: boolean;
            /** Mock Every Days */
            mock_every_days: number;
            /** Booking Overdue */
            booking_overdue: boolean;
        };
        /** ExerciseAnswer */
        ExerciseAnswer: {
            /** Index */
            index: number;
            /** Response */
            response: {
                [key: string]: unknown;
            };
        };
        /** ExerciseOut */
        ExerciseOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "mcq" | "cloze" | "order";
            /** Prompt */
            prompt?: string | null;
            /** Options */
            options?: string[] | null;
            /** Words */
            words?: string[] | null;
            /** Passage */
            passage?: string | null;
            /** Audio Text */
            audio_text?: string | null;
            /** Audio Url */
            audio_url?: string | null;
        };
        /** FeatureSpend */
        FeatureSpend: {
            /** Feature */
            feature: string;
            /** Cost Usd */
            cost_usd: string;
        };
        /** FixOut */
        FixOut: {
            /** Excerpt */
            excerpt: string;
            /** Correction */
            correction: string;
            /** Explanation */
            explanation: string;
        };
        /** FreeAllowance */
        FreeAllowance: {
            /** Model */
            model: string;
            /** Unit */
            unit: string;
            /** Allowance */
            allowance: number;
            /** Used */
            used: number;
        };
        /** GrammarContent */
        GrammarContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "grammar";
            /** Concept Title */
            concept_title: string;
            /** Concept Md */
            concept_md: string;
            /** Exercises */
            exercises: components["schemas"]["ExerciseOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemAnswer */
        ItemAnswer: {
            /** Item Id */
            item_id: string;
            /** Response */
            response: {
                [key: string]: unknown;
            };
            /** Time Ms */
            time_ms?: number | null;
        };
        /** ItemResult */
        ItemResult: {
            /** Correct */
            correct: boolean;
            /** Expected */
            expected: string;
            /** Explanation */
            explanation: string | null;
            /** Item Id */
            item_id: string;
        };
        /** LearnerSettings */
        LearnerSettings: {
            /** Exam Date */
            exam_date?: string | null;
            /**
             * Target Nclc
             * @default 7
             */
            target_nclc: number;
            /**
             * Daily Minutes
             * @default 90
             */
            daily_minutes: number;
            /**
             * Accent Mix
             * @default mixed
             * @enum {string}
             */
            accent_mix: "france" | "quebec" | "mixed";
            /**
             * Timezone
             * @default Asia/Kolkata
             */
            timezone: string;
        };
        /** LessonCompleted */
        LessonCompleted: {
            module: components["schemas"]["ModuleSummary"];
            /** Cards Added */
            cards_added: number;
        };
        /** LessonOut */
        LessonOut: {
            /** Id */
            id: string;
            /** Module Id */
            module_id: string;
            /** Title */
            title: string;
            /** Done */
            done: boolean;
            /** Content */
            content: components["schemas"]["GrammarContent"] | components["schemas"]["VocabContent"] | components["schemas"]["SentencesContent"] | components["schemas"]["ListeningContent"] | components["schemas"]["ReadingContent"] | components["schemas"]["WritingContent"] | components["schemas"]["SpeakingContent"];
        };
        /** LessonSummary */
        LessonSummary: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Done */
            done: boolean;
        };
        /** LevelOut */
        LevelOut: {
            /** Id */
            id: string;
            /** Covered */
            covered: number;
            /** Total */
            total: number;
            /** Modules */
            modules: components["schemas"]["ModuleSummary"][];
        };
        /** ListeningContent */
        ListeningContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "listening";
            /** Transcript */
            transcript: string;
            /** Audio Url */
            audio_url: string | null;
            /** Exercises */
            exercises: components["schemas"]["ExerciseOut"][];
        };
        /** ModuleCheckOut */
        ModuleCheckOut: {
            /** Run Id */
            run_id: number;
            /** Items */
            items: components["schemas"]["CheckItemOut"][];
        };
        /** ModuleDetail */
        ModuleDetail: {
            /** Id */
            id: string;
            /** Order */
            order: number;
            /** Title */
            title: string;
            /** Theme */
            theme: string;
            status: components["schemas"]["Status"];
            /** Lessons Total */
            lessons_total: number;
            /** Lessons Done */
            lessons_done: number;
            /** Check Score */
            check_score: number | null;
            /** Level */
            level: string;
            /** Summary */
            summary: string;
            /** Lessons */
            lessons: components["schemas"]["LessonSummary"][];
            /** Can Take Check */
            can_take_check: boolean;
        };
        /** ModuleSummary */
        ModuleSummary: {
            /** Id */
            id: string;
            /** Order */
            order: number;
            /** Title */
            title: string;
            /** Theme */
            theme: string;
            status: components["schemas"]["Status"];
            /** Lessons Total */
            lessons_total: number;
            /** Lessons Done */
            lessons_done: number;
            /** Check Score */
            check_score: number | null;
        };
        /** NextLesson */
        NextLesson: {
            /** Module Id */
            module_id: string;
            /** Module Title */
            module_title: string;
            /** Lesson Id */
            lesson_id: string;
            /** Lesson Title */
            lesson_title: string;
        };
        /** Passphrase */
        Passphrase: {
            /** Passphrase */
            passphrase: string;
        };
        /** PathOut */
        PathOut: {
            coverage: components["schemas"]["CoverageOut"];
            /** Levels */
            levels: components["schemas"]["LevelOut"][];
            next_lesson: components["schemas"]["NextLesson"] | null;
        };
        /** PlacementOutcome */
        PlacementOutcome: {
            /** Score */
            score: number;
            /** Placed Level */
            placed_level: string;
            /** Modules Placed */
            modules_placed: number;
            /** Levels */
            levels: {
                [key: string]: components["schemas"]["SkillLevelOut"] | null;
            };
        };
        /** ReadingContent */
        ReadingContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "reading";
            /** Text */
            text: string;
            /** Exercises */
            exercises: components["schemas"]["ExerciseOut"][];
        };
        /** ReviewCard */
        ReviewCard: {
            /** Id */
            id: number;
            /** Item Type */
            item_type: string;
            /** Prompt En */
            prompt_en: string;
            /** Answer Fr */
            answer_fr: string;
            /** Gender */
            gender: string | null;
            /** Example Fr */
            example_fr: string | null;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Reviews */
            reviews: number;
        };
        /** ReviewRating */
        ReviewRating: {
            /** Rating */
            rating: number;
        };
        /** SearchHit */
        SearchHit: {
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Source Ref */
            source_ref: string;
            /** Cefr */
            cefr: string | null;
            /** Personal */
            personal: boolean;
        };
        /** SentenceOut */
        SentenceOut: {
            /** Id */
            id: string;
            /** Fr */
            fr: string;
            /** En */
            en: string;
        };
        /** SentencesContent */
        SentencesContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "sentences";
            /** Sentences */
            sentences: components["schemas"]["SentenceOut"][];
        };
        /** ServiceSpend */
        ServiceSpend: {
            /** Cap Usd */
            cap_usd: string;
            /** Spent Usd */
            spent_usd: string;
            /** Reserved Usd */
            reserved_usd: string;
            /** Projected Usd */
            projected_usd: string;
        };
        /** SettingsOut */
        SettingsOut: {
            settings: components["schemas"]["LearnerSettings"];
            plan: components["schemas"]["ExamPlanOut"] | null;
        };
        /** SkillLevelOut */
        SkillLevelOut: {
            /** Skill */
            skill: string;
            /** Score */
            score: number;
            /** Se */
            se: number;
            /** Cefr */
            cefr: string;
            /** Nclc */
            nclc: number | null;
            /** Evidence Count */
            evidence_count: number;
            /**
             * Last At
             * Format: date-time
             */
            last_at: string;
            /** Stale */
            stale: boolean;
        };
        /** SpeakingContent */
        SpeakingContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "speaking";
            /** Task */
            task: string;
            /** Prompt */
            prompt: string;
            /** Seconds */
            seconds: number;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "locked" | "open" | "covered" | "placed";
        /** TaggedErrorOut */
        TaggedErrorOut: {
            /** Tag */
            tag: string;
            /** Excerpt */
            excerpt: string;
            /** Correction */
            correction: string;
        };
        /** UsageEventOut */
        UsageEventOut: {
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Service */
            service: string;
            /** Model */
            model: string;
            /** Feature */
            feature: string;
            /** Units */
            units: {
                [key: string]: number;
            };
            /** Free Units */
            free_units: {
                [key: string]: number;
            };
            /** Cost Usd */
            cost_usd: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VocabContent */
        VocabContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "vocab";
            /** Words */
            words: components["schemas"]["WordOut"][];
        };
        /** WordOut */
        WordOut: {
            /** Id */
            id: string;
            /** Lemma */
            lemma: string;
            /** Pos */
            pos: string;
            /** Gender */
            gender: string | null;
            /** En */
            en: string;
            /** Example Fr */
            example_fr: string;
            /** Example En */
            example_en: string;
        };
        /** WritingContent */
        WritingContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "writing";
            /** Task */
            task: string;
            /** Prompt */
            prompt: string;
            /** Min Words */
            min_words: number;
            /** Max Words */
            max_words: number;
        };
        /** WritingDrillOut */
        WritingDrillOut: {
            /** Run Id */
            run_id: number;
            /** Task */
            task: string;
            /** Prompt */
            prompt: string;
            /** Min Words */
            min_words: number;
            /** Max Words */
            max_words: number;
            /**
             * Deadline
             * Format: date-time
             */
            deadline: string;
        };
        /** WritingResult */
        WritingResult: {
            /** Id */
            id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "graded";
            /** Task */
            task: string;
            /** Word Count */
            word_count: number;
            /** Score */
            score: number | null;
            /** Criteria */
            criteria: {
                [key: string]: number;
            };
            /** Evidence */
            evidence: {
                [key: string]: string;
            };
            /** Fixes */
            fixes: components["schemas"]["FixOut"][];
            /** Errors */
            errors: components["schemas"]["TaggedErrorOut"][];
            level?: components["schemas"]["SkillLevelOut"] | null;
        };
        /** WritingText */
        WritingText: {
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    status_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Passphrase"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Passphrase"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_summary_budget_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_caps_budget_caps_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_budget_events_get: {
        parameters: {
            query?: {
                limit?: number;
                feature?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_path_path_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_module_modules__module_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: string;
            };
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_check_modules__module_id__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: string;
            };
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_check_checks__run_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckOutcome"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_lessons__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_exercise_lessons__lesson_id__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseAnswer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_lesson_lessons__lesson_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonCompleted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    due_reviews_reviews_due_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCard"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rate_card_reviews__card_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRating"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    learned_words_library_words_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    learned_sentences_library_sentences_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentenceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    learned_concepts_library_concepts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skills_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["SkillLevelOut"] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_drill_drills_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrillStart"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrillOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_drill_drills__run_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrillOutcome"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_placement_placement_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrillOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_placement_placement__run_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOutcome"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearnerSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_lesson_writing_lessons__lesson_id__writing_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritingText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_writing_drill_writing_drills_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritingDrillOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_writing_drill_writing_drills__run_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritingText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    error_fingerprint_errors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorFingerprintOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
                scope?: "learned" | "catalogue" | "mine";
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                mf_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
