"""repeat after me

Revision ID: f4cf72d34652
Revises: 23f267ea3587
Create Date: 2026-10-10 18:44:48.342178

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f4cf72d34652"
down_revision: str | Sequence[str] | None = "23f267ea3587"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repeat_sets",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("focus", sa.String(), nullable=False),
        sa.Column("cefr", sa.String(length=2), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repeat_sets")),
    )
    op.create_table(
        "repeat_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sentence_id", sa.String(length=80), nullable=False),
        sa.Column("reference", sa.Text(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("accuracy", sa.Double(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_repeat_attempts_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repeat_attempts")),
    )
    op.create_index(
        op.f("ix_repeat_attempts_sentence_id"), "repeat_attempts", ["sentence_id"], unique=False
    )
    op.create_index(
        op.f("ix_repeat_attempts_user_id"), "repeat_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "repeat_sentences",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("set_id", sa.String(length=80), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("fr", sa.Text(), nullable=False),
        sa.Column("en", sa.Text(), nullable=False),
        sa.Column("tip", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["set_id"], ["repeat_sets.id"], name=op.f("fk_repeat_sentences_set_id_repeat_sets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repeat_sentences")),
    )
    op.create_index(
        op.f("ix_repeat_sentences_set_id"), "repeat_sentences", ["set_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repeat_sentences_set_id"), table_name="repeat_sentences")
    op.drop_table("repeat_sentences")
    op.drop_index(op.f("ix_repeat_attempts_user_id"), table_name="repeat_attempts")
    op.drop_index(op.f("ix_repeat_attempts_sentence_id"), table_name="repeat_attempts")
    op.drop_table("repeat_attempts")
    op.drop_table("repeat_sets")
    # ### end Alembic commands ###
