"""knowledge base

Revision ID: 6e6cfa541961
Revises: 930075d836c6
Create Date: 2026-09-28 11:32:45.551126

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6e6cfa541961"
down_revision: str | Sequence[str] | None = "930075d836c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # unaccent() is only STABLE; generated columns and indexes need an IMMUTABLE wrapper.
    op.execute(
        "CREATE FUNCTION immutable_unaccent(text) RETURNS text "
        "LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT "
        "AS $$ SELECT public.unaccent('public.unaccent', $1) $$"
    )
    op.create_table(
        "kb_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("module_id", sa.String(length=80), nullable=True),
        sa.Column("cefr", sa.String(length=2), nullable=True),
        sa.Column("source_ref", sa.String(length=200), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('french', immutable_unaccent(title || ' ' || text))", persisted=True
            ),
            nullable=False,
        ),
        sa.Column(
            "title_norm",
            sa.Text(),
            sa.Computed("immutable_unaccent(lower(title))", persisted=True),
            nullable=False,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=512), nullable=True),
        sa.Column("embedding_model", sa.String(length=60), nullable=True),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], name=op.f("fk_kb_entries_module_id_modules")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_kb_entries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kb_entries")),
        sa.UniqueConstraint("key", name=op.f("uq_kb_entries_key")),
    )
    op.create_index(
        "ix_kb_entries_title_norm",
        "kb_entries",
        ["title_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_kb_entries_tsv", "kb_entries", ["tsv"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_kb_entries_user_id"), "kb_entries", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kb_entries_user_id"), table_name="kb_entries")
    op.drop_index("ix_kb_entries_tsv", table_name="kb_entries", postgresql_using="gin")
    op.drop_index(
        "ix_kb_entries_title_norm",
        table_name="kb_entries",
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.drop_table("kb_entries")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION immutable_unaccent(text)")
