"""writing submissions and error tags

Revision ID: 930075d836c6
Revises: b01b2e602e3e
Create Date: 2026-09-28 11:17:57.368373

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "930075d836c6"
down_revision: str | Sequence[str] | None = "b01b2e602e3e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "error_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=30), nullable=False),
        sa.Column("example", sa.Text(), nullable=False),
        sa.Column("correction", sa.Text(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_error_tags_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_error_tags")),
        sa.UniqueConstraint("user_id", "tag", name=op.f("uq_error_tags_user_id")),
    )
    op.create_table(
        "writing_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("lesson_id", sa.String(length=160), nullable=True),
        sa.Column("item_id", sa.String(length=160), nullable=True),
        sa.Column("task", sa.String(length=4), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("score", sa.Double(), nullable=True),
        sa.Column("rubric", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_writing_submissions_item_id_items")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["assessment_runs.id"],
            name=op.f("fk_writing_submissions_run_id_assessment_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_writing_submissions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_writing_submissions")),
    )
    op.create_index(
        op.f("ix_writing_submissions_user_id"), "writing_submissions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_writing_submissions_user_id"), table_name="writing_submissions")
    op.drop_table("writing_submissions")
    op.drop_table("error_tags")
    # ### end Alembic commands ###
