"""glossaries

Revision ID: 23f267ea3587
Revises: e8f7cbe8442c
Create Date: 2026-10-01 15:54:19.719945

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "23f267ea3587"
down_revision: str | Sequence[str] | None = "e8f7cbe8442c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "module_glossaries",
        sa.Column("module_id", sa.String(length=80), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("entries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], name=op.f("fk_module_glossaries_module_id_modules")
        ),
        sa.PrimaryKeyConstraint("module_id", name=op.f("pk_module_glossaries")),
    )
    op.add_column(
        "notes", sa.Column("glossary", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes", "glossary")
    op.drop_table("module_glossaries")
    # ### end Alembic commands ###
