"""initial schema

Revision ID: b01b2e602e3e
Revises:
Create Date: 2026-09-28 04:42:08.961699

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b01b2e602e3e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "levels",
        sa.Column("id", sa.String(length=2), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_levels")),
        sa.UniqueConstraint("order", name=op.f("uq_levels_order")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("passphrase_hash", sa.String(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "assessment_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("scope_id", sa.String(length=160), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score", sa.Double(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_assessment_runs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_runs")),
    )
    op.create_index(
        op.f("ix_assessment_runs_user_id"), "assessment_runs", ["user_id"], unique=False
    )
    op.create_table(
        "blocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("level_id", sa.String(length=2), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["level_id"], ["levels.id"], name=op.f("fk_blocks_level_id_levels")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blocks")),
        sa.UniqueConstraint("level_id", "order", name=op.f("uq_blocks_level_id")),
    )
    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("service", sa.String(length=10), nullable=False),
        sa.Column("cap_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_budgets_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
        sa.UniqueConstraint("user_id", "month", "service", name=op.f("uq_budgets_user_id")),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("item_type", sa.String(length=10), nullable=False),
        sa.Column("item_id", sa.String(length=160), nullable=False),
        sa.Column("fsrs_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviews", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_cards_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
        sa.UniqueConstraint("user_id", "item_type", "item_id", name=op.f("uq_cards_user_id")),
    )
    op.create_index(op.f("ix_cards_due_at"), "cards", ["due_at"], unique=False)
    op.create_index(op.f("ix_cards_user_id"), "cards", ["user_id"], unique=False)
    op.create_table(
        "usage_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("service", sa.String(length=10), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("feature", sa.String(length=30), nullable=False),
        sa.Column("units", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("free_units", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("price_version", sa.String(length=20), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_usage_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_events")),
    )
    op.create_index(
        op.f("ix_usage_events_occurred_at"), "usage_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "budget_reservations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("service", sa.String(length=10), nullable=False),
        sa.Column("feature", sa.String(length=30), nullable=False),
        sa.Column("estimated_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_event_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["usage_event_id"],
            ["usage_events.id"],
            name=op.f("fk_budget_reservations_usage_event_id_usage_events"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_budget_reservations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_reservations")),
    )
    op.create_index(
        op.f("ix_budget_reservations_settled_at"),
        "budget_reservations",
        ["settled_at"],
        unique=False,
    )
    op.create_table(
        "modules",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("block_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("theme", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"], ["blocks.id"], name=op.f("fk_modules_block_id_blocks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modules")),
        sa.UniqueConstraint("order", name=op.f("uq_modules_order")),
    )
    op.create_table(
        "concepts",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("module_id", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], name=op.f("fk_concepts_module_id_modules")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concepts")),
    )
    op.create_index(op.f("ix_concepts_module_id"), "concepts", ["module_id"], unique=False)
    op.create_table(
        "items",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.String(length=160), nullable=True),
        sa.Column("module_id", sa.String(length=80), nullable=True),
        sa.Column("skill", sa.String(length=2), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("cefr", sa.String(length=2), nullable=False),
        sa.Column("difficulty", sa.Double(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("audio_hash", sa.String(length=64), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], name=op.f("fk_items_module_id_modules")
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"], ["items.id"], name=op.f("fk_items_supersedes_id_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
    )
    op.create_index(op.f("ix_items_key"), "items", ["key"], unique=False)
    op.create_index(op.f("ix_items_module_id"), "items", ["module_id"], unique=False)
    op.create_table(
        "lessons",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("module_id", sa.String(length=80), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], name=op.f("fk_lessons_module_id_modules")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
    )
    op.create_index(op.f("ix_lessons_module_id"), "lessons", ["module_id"], unique=False)
    op.create_table(
        "lexemes",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("module_id", sa.String(length=80), nullable=False),
        sa.Column("lemma", sa.String(), nullable=False),
        sa.Column("pos", sa.String(length=20), nullable=False),
        sa.Column("gender", sa.String(length=1), nullable=True),
        sa.Column("en", sa.String(), nullable=False),
        sa.Column("example_fr", sa.String(), nullable=False),
        sa.Column("example_en", sa.String(), nullable=False),
        sa.Column("audio_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], name=op.f("fk_lexemes_module_id_modules")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lexemes")),
    )
    op.create_index(op.f("ix_lexemes_module_id"), "lexemes", ["module_id"], unique=False)
    op.create_table(
        "module_progress",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.String(length=80), nullable=False),
        sa.Column("lessons_done", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("check_score", sa.Double(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("covered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], name=op.f("fk_module_progress_module_id_modules")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_module_progress_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", "module_id", name=op.f("pk_module_progress")),
    )
    op.create_table(
        "sentences",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("module_id", sa.String(length=80), nullable=False),
        sa.Column("fr", sa.Text(), nullable=False),
        sa.Column("en", sa.Text(), nullable=False),
        sa.Column("audio_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], name=op.f("fk_sentences_module_id_modules")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sentences")),
    )
    op.create_index(op.f("ix_sentences_module_id"), "sentences", ["module_id"], unique=False)
    op.create_table(
        "responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.String(length=160), nullable=False),
        sa.Column("skill", sa.String(length=2), nullable=False),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("time_ms", sa.Integer(), nullable=True),
        sa.Column("timed_out", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], name=op.f("fk_responses_item_id_items")),
        sa.ForeignKeyConstraint(
            ["run_id"], ["assessment_runs.id"], name=op.f("fk_responses_run_id_assessment_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_responses")),
    )
    op.create_index(op.f("ix_responses_run_id"), "responses", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_responses_run_id"), table_name="responses")
    op.drop_table("responses")
    op.drop_index(op.f("ix_sentences_module_id"), table_name="sentences")
    op.drop_table("sentences")
    op.drop_table("module_progress")
    op.drop_index(op.f("ix_lexemes_module_id"), table_name="lexemes")
    op.drop_table("lexemes")
    op.drop_index(op.f("ix_lessons_module_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_items_module_id"), table_name="items")
    op.drop_index(op.f("ix_items_key"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_concepts_module_id"), table_name="concepts")
    op.drop_table("concepts")
    op.drop_table("modules")
    op.drop_index(op.f("ix_budget_reservations_settled_at"), table_name="budget_reservations")
    op.drop_table("budget_reservations")
    op.drop_index(op.f("ix_usage_events_occurred_at"), table_name="usage_events")
    op.drop_table("usage_events")
    op.drop_index(op.f("ix_cards_user_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_due_at"), table_name="cards")
    op.drop_table("cards")
    op.drop_table("budgets")
    op.drop_table("blocks")
    op.drop_index(op.f("ix_assessment_runs_user_id"), table_name="assessment_runs")
    op.drop_table("assessment_runs")
    op.drop_table("users")
    op.drop_table("levels")
    # ### end Alembic commands ###
