"""class notes and note items

Revision ID: e93c500cbab9
Revises: 81e16d2c2c36
Create Date: 2026-09-30 14:59:38.681327

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e93c500cbab9"
down_revision: str | Sequence[str] | None = "81e16d2c2c36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("day", sa.Integer(), nullable=True),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_notes_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
        sa.UniqueConstraint("user_id", "content_hash", name=op.f("uq_notes_user_id")),
    )
    op.create_index(op.f("ix_notes_user_id"), "notes", ["user_id"], unique=False)
    op.create_table(
        "note_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("fr", sa.Text(), nullable=False),
        sa.Column("en", sa.Text(), nullable=False),
        sa.Column("gender", sa.String(length=1), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("key", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["note_id"], ["notes.id"], name=op.f("fk_note_items_note_id_notes")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_note_items_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_note_items")),
    )
    op.create_index(op.f("ix_note_items_key"), "note_items", ["key"], unique=False)
    op.create_index(op.f("ix_note_items_note_id"), "note_items", ["note_id"], unique=False)
    op.create_index(op.f("ix_note_items_user_id"), "note_items", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_note_items_user_id"), table_name="note_items")
    op.drop_index(op.f("ix_note_items_note_id"), table_name="note_items")
    op.drop_index(op.f("ix_note_items_key"), table_name="note_items")
    op.drop_table("note_items")
    op.drop_index(op.f("ix_notes_user_id"), table_name="notes")
    op.drop_table("notes")
    # ### end Alembic commands ###
