"""drop unused audio hash columns

Revision ID: 81e16d2c2c36
Revises: b2e0f65db2c4
Create Date: 2026-09-29 11:42:29.975341

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81e16d2c2c36"
down_revision: str | Sequence[str] | None = "b2e0f65db2c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "audio_hash")
    op.drop_column("lexemes", "audio_hash")
    op.drop_column("sentences", "audio_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sentences",
        sa.Column("audio_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.add_column(
        "lexemes",
        sa.Column("audio_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.add_column(
        "items", sa.Column("audio_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
