"""skill on submissions

Revision ID: e8f7cbe8442c
Revises: e93c500cbab9
Create Date: 2026-10-01 03:10:25.363163

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8f7cbe8442c"
down_revision: str | Sequence[str] | None = "e93c500cbab9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "writing_submissions",
        sa.Column("skill", sa.String(length=2), server_default="EE", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("writing_submissions", "skill")
    # ### end Alembic commands ###
